### ISSUE TITLE
Cannot find declaration when using defdelegate

### ISSUE THREAD

**Issue by mezz** [KronicDeth/intellij-elixir#1613]
**Describe the bug**
I am able to navigate to Declaration of anything created with `def`, but not with `defdelegate`.

**To Reproduce**
1. Create a function using `def`, and one using `defdelegate`.
2. Create some code that uses the two functions.
2. Cmd-Click (on mac) a usage of each function to navigate to the declaration.
3. You will be able to navigate to the Declaration of the `def` function, but not the `defdelegate` function.

**Expected behavior**
I expect to be able to jump to the Declaration of the `defdelegate`.

**Screenshots**
Screenshot of the result of Cmd-Clicking a usage of a `defdelegate` function:
![Screen Shot 2019-10-31 at 11 20 37 AM](https://user-images.githubusercontent.com/916092/67974924-7cf96800-fbd0-11e9-90b5-bbbdff9d29f9.png)

**Desktop:**
 - OS: macOS
 - Version 10.14.6

**Erlang:**
- Installer: homebrew
- Version 21

**Elixir:**
- Installer: homebrew
- Version 1.7.3

**Plugin:**
- Version 11.2.0

**Comment by sh41** [comment]
This was fixed after you filed it. Resolving a call through `defdelegate` was added in 811753ac3 ("Resolve references through defdelegate calls") and first shipped in v11.11.0 — you reported it on 11.2.0.

Verified on current `main` with your setup: a `def` in one module, a `defdelegate` to it in a second, and a call from a third. Cmd-Click on the call navigates.

One difference from what you asked for, and it's deliberate: it lands on the real `def` in the `to:` module rather than on the `defdelegate` line. The `defdelegate` head does still resolve as a declaration of `delegated/1` in its own module, so Find Usages and Rename see both.

Closed as part of an AI-assisted review of the backlog. A human checked this one before closing it, but it might still be a mistake. If you think the reason above is wrong, please reopen the issue and tell us why.

**Comment by nick-lunar** [comment]
it may or may not be still broken in master,  my example  is `Map.new` (vanilla `def` - intellisense works) and `Map.values` (`defdelegate` - doesn't work) coming from the same module.  The `Map` module itself works / interactive. 

Tried

*  24.0.1  - last public release,  
* and [25.0.1-pre+20260902134330.88abab48.zip](https://github.com/user-attachments/files/31742074/intellij-elixir-25.0.1-pre%2B20260902134330.88abab48.zip) same behavior

<img width="1172" height="212" alt="Image" src="https://github.com/user-attachments/assets/d6a47827-a3bb-4958-a205-6805e1282900" />

<img width="1610" height="250" alt="Image" src="https://github.com/user-attachments/assets/675f4c44-8d7f-40e6-a4a9-efe9cebfca22" />

<img width="1548" height="348" alt="Image" src="https://github.com/user-attachments/assets/f3fa801a-87f5-4f36-8065-8d2a30058f9c" />

**Comment by nick-lunar** [comment]
some more observations.  I think all symbols are present in the cache, plugins just doesn't connect the dots. 

`Map.merge` is similar to `Map.values` - also a `defdelegate` , also won't show docs nor Go to Definition: 

<img width="496" height="112" alt="Image" src="https://github.com/user-attachments/assets/67a2bec1-b95f-4f61-ad49-3d03d0737196" />

but shows up in autocomplete :

<img width="701" height="139" alt="Image" src="https://github.com/user-attachments/assets/d7b68527-00b2-47d3-8884-47d61a575d9d" />


whereas `Map.values` is not in autocomplete:

<img width="433" height="107" alt="Image" src="https://github.com/user-attachments/assets/6ae796e5-7dda-4386-a09c-280282ff4f0b" />


but there's more! did you spot that `v` is italic like if it's recognized as a proper symbol? Because it is! and so do `va` , `val`, `valu` and `value` - basically all partial substrings of `values` - and they all point to exact same map.values in erlang

<img width="715" height="184" alt="Image" src="https://github.com/user-attachments/assets/34dc67e5-c2a4-4215-a284-56836585fd13" />

And only when it is full `values` it becomes non-italic and anemic again:

<img width="602" height="105" alt="Image" src="https://github.com/user-attachments/assets/ce56aa28-ed1f-4c60-b3be-e30ce37c96e4" />


upon Cmd+Click `v`, `va` etc. to `value`  offers two options - the erlang's map values and, for some non-obvious reason, also one isolated `values` token in ... ecto's query.ex (second)

<img width="511" height="160" alt="Image" src="https://github.com/user-attachments/assets/bea6043c-b8e7-4a4d-9caa-961193923c9c" />


First option goes here:

<img width="770" height="170" alt="Image" src="https://github.com/user-attachments/assets/e2d46841-df59-476a-97fb-3b32679bec5b" />


The ecto usage, Go to Definition lands on selected `value` in `query, value)` 

<img width="879" height="138" alt="Image" src="https://github.com/user-attachments/assets/2ca3149a-744c-4041-87c2-cd62bd9eee86" />

**Comment by nick-lunar** [comment]
and apparently that `v` to `value` phenomenon only shows up with pipe operator `|> Map.` ,  if it's just `Map.v` etc. then nope, just anemic letters.   And I was unable to get the weird ecto query.ex destination phenomenon anywhere but one file which I spot checked, so I wouldn't ruminate too much on that one. 

In fact maybe this is all about parsing of pipes and/or partial application? I noticed that all my piped usages of merge like `|> Map.merge(...` are anemic but normal full call to `Map.merge` is interactive and even go-to clickable.  But same non-piped `Map.values` is stubbornly anemic still.

<img width="792" height="102" alt="Image" src="https://github.com/user-attachments/assets/159624b2-06e1-4e78-b009-9aca7bb7ff75" />

and yet invalid call to `Map.merge()` without argument still offers a tooltip, but not clickable.

<img width="730" height="141" alt="Image" src="https://github.com/user-attachments/assets/6831429e-350b-4f08-ac60-7cba12b2004f" />

Ok, hopefully enough random symptoms to identify root cause. 


---
Last random thought, in case if it by any chance relates to introduction of gradual typing or similar. My SDK paths are: 

/Users/nick/.asdf/installs/elixir/1.20.2-otp-29
/Users/nick/.asdf/installs/erlang/29.0.2

**Comment by sh41** [comment]
@nick-lunar, thank you again for the excellent issue reports. They save hours of tracking down reproductions.

The `merge` versus `values` comparison is what found it. Both delegate to `:maps`, which exists only as a `.beam`, and the plugin never followed a `defdelegate` into compiled code. `merge` showed up in autocomplete only because `Map.merge/3` is separately a real `def`.

Fixed on `main` in [`bdff12642`](https://github.com/KronicDeth/intellij-elixir/commit/bdff12642) (#4039). Not released yet & will be in the next release, but you can try the dev build here if you want:

[intellij-elixir-25.0.1-pre+20260908142206.614bd427.zip](https://github.com/user-attachments/files/31965519/intellij-elixir-25.0.1-pre%2B20260908142206.614bd427.zip)

Just so you know: Compiled `.beam` functions are second-class across the whole plugin, not only in delegation. That is tracked under #4044 and is a long job: expect it to improve in steps rather than all at once.

### Should work now

For any `defdelegate` pointing at a compiled module (`Map.values`, `Map.merge`, and the rest of the stdlib):
- **Go To Declaration**: skips the `defdelegate` line and lands on the real definition in the `.beam`
- **Quick Documentation**: shows the defdelegate statement's doc, or if there isn't one, the target `.beam` doc.
- **Autocomplete**: offers the name at all - `values` was previously missing entirely, and `merge` appeared with no signature - now with its parameters in the completion popup, inserting `()` after completion.

Your piped `|> Map.merge(...)` case is fixed by this & the italic `v` / `va` / `val` oddity should go too. That was IntelliJ's own name-guessing fallback filling in because the plugin returned nothing for the real name.

### Still broken

Known and tracked, not fixed by this:

- **Find Usages and Rename** on a delegated name - offered, but silently do nothing → #4043
- **Parameter hints** in a delegated call → #4043
- **Parameter hints for *any* Erlang / `.beam` function** → #4048
- `defdelegate [foo(a), bar(b)], to: M`, the deprecated list form → #4040

**Comment by nick-lunar** [comment]
looks good, thanks!  both `Map.merge` and `Map.values` are resolved/interactive and appear in autocomplete too,  plain or via a `|>` pipe operator. Keeping this pre-release for myself :) No screenshots needed I think.

Yep "Find usages" doesn't find anything - good to know it's known and tracked.

**Comment by nick-lunar** [comment]
actually partial v / va / val oddity still appear but only in piped `|> Map.v` as you can see below.  And it's only `values` (parameterless?), not fully typed `merge` in the very same source and line is perfectly anemic like it should be.  Either way it's relatively minor symptom not the main issue that seems fixed now.

<img width="699" height="170" alt="Image" src="https://github.com/user-attachments/assets/b5423808-53c7-408a-b326-2df8bc7d3ad8" />

<img width="368" height="98" alt="Image" src="https://github.com/user-attachments/assets/ee13a129-bdc7-44c4-943c-0a1aa559087e" />
