### ISSUE TITLE
Parameter info

### ISSUE THREAD

**Issue by trucndt** [KronicDeth/intellij-elixir#1627]
The show parameter is only valid when the parameters are filled. For example, if I type
```elixir
Process.flag(:trap_exit, true)
```
then the `Ctrl + P` shows `p0, p1`

However, if I type:
```elixir
Process.flag()
```
then the `Ctrl + P` doesn't show anything. For Java or C++, in this case, it should show the suggested parameters. I hope you can add this feature

Thanks

**Comment by KronicDeth** [comment]
This was fixed by https://github.com/KronicDeth/intellij-elixir/pull/1617, which was released in [11.4.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v11.4.0) a few minutes ago.

**Comment by trucndt** [comment]
Hello, I updated to version 11.4.0 and the Show Parameter still doesn't work as the case I showed above.

Thanks.

**Comment by KronicDeth** [comment]
Oh, yeah, you're right.  The change I made seems to only affect unqualified calls and not qualified calls.  I'll have to figure out what I missed changing for qualified calls.
